defaultSettings:
  kubernetesClusterAutoscalerEnabled: true

  autoDeletePodWhenVolumeDetachedUnexpectedly: true

  nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"

  nodeDrainPolicy: "block-if-contains-last-replica"

  detachManuallyAttachedVolumesWhenCordoned: true

  disableSchedulingOnCordonedNode: true

  replicaReplenishmentWaitInterval: 600

  allowVolumeCreationWithDegradedAvailability: false

  autoSalvage: true

  defaultReplicaCount: 3

  storageOverProvisioningPercentage: 100

  replicaAutoBalance: "best-effort"

persistence:
  defaultClassReplicaCount: 3 # StorageClass volumes
  defaultClass: true
  defaultDataLocality: "best-effort"
