defaultSettings:
  kubernetesClusterAutoscalerEnabled: true

  autoDeletePodWhenVolumeDetachedUnexpectedly: true

  nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"

  nodeDrainPolicy: "block-if-contains-last-replica"

  detachManuallyAttachedVolumesWhenCordoned: true

  disableSchedulingOnCordonedNode: true

  replicaReplenishmentWaitInterval: 600

  allowVolumeCreationWithDegradedAvailability: false

  autoSalvage: true

  defaultReplicaCount: 2

  storageOverProvisioningPercentage: 100

  replicaAutoBalance: "best-effort"

  recurringBackupJobConcurrency: 2

  backupCompressionMethod: "gzip"

  v2DataEngine: false

defaultBackupStore:
  backupTarget: "s3://longhorn-backup-talos@us-east-1/talos/"
  backupTargetCredentialSecret: "longhorn-backup-secret"
persistence:
  defaultClassReplicaCount: 2 # StorageClass volumes
  defaultClass: true
  defaultDataLocality: "best-effort"
