# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: external-secrets-configs
#   namespace: flux-system
# spec:
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/configs/base/external-secret
#   prune: true

# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cert-manager-config
#   namespace: flux-system
# spec:
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/configs/base/cert-manager
#   prune: true

# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: certificates
#   namespace: flux-system
# spec:
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/configs/base/certificates
#   prune: true
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: istio-config
#   namespace: flux-system
# spec:
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/configs/base/istio
#   prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-config
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs/base/longhorn
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: velero-config
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs/base/velero
  prune: true
