# Increase memory limit to prevent excessive cache clearing
resources:
  limits:
    memory: 256Mi

spegel:
  mirroredRegistries:
    - https://docker.io
    - https://registry.k8s.io # Kubernetes components
    - https://ghcr.io
    - https://quay.io

# Enable monitoring
serviceMonitor:
  enabled: false

# Enable Grafana dashboard
grafanaDashboard:
  enabled: false 
