---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-wildcard
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: local@fedora.io
    privateKeySecretRef:
      name: letsencrypt-production-wildcard
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token
        selector:
          dnsZones:
            - "sirpify.com"
