---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-wildcard
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: local@fedora.io
    privateKeySecretRef:
      name: letsencrypt-production-wildcard
    solvers:
      - dns01:
          webhook:
            groupName: acme.mycompany.com
            solverName: godaddy
            config:
              apiKeySecretRef:
                name: godaddy-dns
                key: api-key
              apiSecretSecretRef:
                name: godaddy-dns
                key: api-secret
              production: true
              ttl: 600
        selector:
          dnsZones:
            - "luzero.online"
