---
apiVersion: external-secret.io/v1
kind: ExternalSecret
metadata:
   name: digitalocean-dns
   namespce: cert-manager
spec:
   refreshInterval: 1h
   secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
   data:
      - secretKey: access-token
        remoteRef:
           key: kv/data/digital-ocean
           property: DO_TOKEN
