---
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: godaddy-dns
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: godaddy-dns
  data:
    - secretKey: api-key
      remoteRef:
        key: kv/data/godady
        property: key
    - secretKey: api-secret
      remoteRef:
        key: kv/data/godady
        property: secret
