---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: dataplane-ha-api-gtw
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDaemonSet: {}
      envoyPDB:
        minAvailable: 1
      envoyService:
        annotations:
          service.beta.kubernetes.io/zone-awareness: "true"
        type: LoadBalancer
        externalTrafficPolicy: Local
