---
# Gateway Configuration
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: api-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy-gateway
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: dataplane-ha-api-gtw
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
      service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0e8c1253c953de861,subnet-054462a343ba88e56,subnet-03ca2a54546ccf108"
      external-dns.alpha.kubernetes.io/hostname: "grafana.luzero.online"
      external-dns.alpha.kubernetes.io/ttl: "300"
  listeners:
    - name: https
      hostname: "*.luzero.online"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-tls
            namespace: certificates
            kind: Secret
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
              - key: app.kubernetes.io/environment
                operator: In
                values:
                  - monitoring
    - name: http
      hostname: "*.luzero.online"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
              - key: app.kubernetes.io/environment
                operator: In
                values:
                  - monitoring
