provider:
  name: godaddy

policy: upsert-only

env:
  - name: GODADDY_API_KEY
    valueFrom:
      secretKeyRef:
        name: godaddy-dns
        key: api-key
  - name: GODADDY_API_SECRET
    valueFrom:
      secretKeyRef:
        name: godaddy-dns
        key: api-secret

domainFilters:
  - luzero.online

txtPrefix: externaldns-

managedRecordTypes:
  - A
  - CNAME
#logLevel: debug

interval: 1h
sources:
  - service
  - ingress
  - gateway-httproute
  - gateway-grpcroute
  - gateway-tcproute
