provider:
  name: digitalocean

policy: upsert-only

env:
  - name: DO_TOKEN
    valueFrom:
      secretKeyRef:
        name: do-token
        key: DO_TOKEN

domainFilters:
  - sirpify.com

txtPrefix: externaldns-

managedRecordTypes:
  - A
  - CNAME

#logLevel: debug

interval: 1h

sources:
  - service
  - ingress
  - gateway-httproute
  - gateway-grpcroute
  - gateway-tcproute
