provider:
  name: cloudflare

policy: upsert-only

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token

domainFilters:
  - luzero.online

txtPrefix: externaldns-

managedRecordTypes:
  - A
  - CNAME
#logLevel: debug
interval: 1h
sources:
  - service
  - ingress
  - gateway-httproute
  - gateway-grpcroute
  - gateway-tcproute
