---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wv-wildcard
  namespace: certificates
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-production-wildcard
    kind: ClusterIssuer
  dnsNames:
    - "*.luzero.online"
    - "luzero.online"
