apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - repository.yaml
  - loki-release.yaml
  - alloy-release.yaml

configMapGenerator:
  - name: alloy-config
    files:
      - values.yaml=alloy-values.yaml
  - name: loki-values
    files:
      - values.yaml=loki-values.yaml

configurations:
  - kustomizeconfig.yaml
