apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system

resources:
  - namespace.yaml
  - repository.yaml
  - istio-base-release.yaml
  - istiod-release.yaml
  - istio-gateway.yaml
configMapGenerator:
  - name: istio-values
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml
