---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-promethues-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "77.*"
      interval: 12h
      sourceRef:
        name: kube-promethues-stack
        kind: HelmRepository
        namespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-values
  install:
    crds: create
  upgrade:
    crds: CreateReplace
    timeout: 15m
    remediation:
      retries: 2
      strategy: rollback
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
